### ISSUE TITLE
None Values Not Overriding Index Record for Accounts

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#333]
### Issue

The index record has the canceled_at from when this nft first changed hands at this price to these wallets but the on-chain record has correctly been zeroed out to None (see screenshot). 

```
dbfkoprhnh65jt=> SELECT * FROM listing_receipts WHERE address = '5U9ZPq1aH8GLiB6GQY2Y3DYFxoRYokWSQ23WUQJ3X7uG';
-[ RECORD 1 ]----+---------------------------------------------
address          | 5U9ZPq1aH8GLiB6GQY2Y3DYFxoRYokWSQ23WUQJ3X7uG
trade_state      | 2WY4nhPgfChXJa5ez5JM5Vda53k9t9JyAwLn9kmsRxPD
bookkeeper       | 9ZB1emke9S4Gyhofcds3AN4XVf5FT9McMd3SkA7MF11A
auction_house    | 9cCXJPiwjKTrEDWv6cgxHNeE7m7XK5YbzVfr4ZTBcn9
seller           | 9ZB1emke9S4Gyhofcds3AN4XVf5FT9McMd3SkA7MF11A
metadata         | 7TDxjP4nnmZ6nKBQiP4h531FbwSMUBTBWbXyb8mREzp9
purchase_receipt |
price            | 10000000
token_size       | 1
bump             | 255
trade_state_bump | 254
created_at       | 2022-04-01 16:31:32
canceled_at      | 2022-03-18 18:20:58
```

![Screen Shot 2022-04-01 at 9 50 38 AM](https://user-images.githubusercontent.com/2388118/161307769-6ab3c217-4e2b-4a79-bdc7-e2a60424ed48.png)

### Goal
The indexed record always matches the on-chain account. canceled_at should be null in this case.

**Comment by kespinola** [comment]
We recently added the respect none as null on our models so this may be a missed index run as well.

**Comment by ray-kast** [comment]
Marking as resolved, unless otherwise specified.
