### ISSUE TITLE
Track Current NFT Owner

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#374]
## Background

We currently track token_accounts for the spl mint of the metadata. When the token_account amount is 1 then its wallet has ownership over the NFT. 

## Problems
- If token accounts are closed then it prevents the previous owner from being cleared away. 
- Joining in token accounts to metadata by mint requires a nest loop over token_accounts to find the owner which slows ownership queries.
- Token accounts is a very large table and slow to scan through since it tracks all current and past owners of an NFT.

## Proposal
- Track current owners in a dedicated table. `current_metadata_owners`. When a token account is processed by indexer check if its amount is 1 and if the slot time of the token_account change is larger than the current slot_number on current_metadata_owners update the record with the new owner and slot number.
```
create table current_metadata_owners {
  mint_address varchar(48) primary key
  owner_address varchar(48)
  slot_number init 
}
```
- If we want to track past owners then add db trigger to metadata_owners that saves the previous owner, its slot_number, and transfered_at which is the current time in a dedicated table called `previous_metadata_owners`.

**Comment by imabdulbasit** [comment]
https://github.com/holaplex/indexer/pull/375

do we need past owners? I haven't added a trigger for it
