### ISSUE TITLE
Can't run the services holaplex-indexer-geyser, --amqp-url arguments not working

### ISSUE THREAD

**Issue by shohidulbari** [holaplex/indexer#503]
I tried to run the indexer in my machine, I did everything that is mentioned in readme.md. But getting this type error. Can anyone tell what is wrong here,
![Screenshot from 2022-06-01 02-49-40](https://user-images.githubusercontent.com/48408380/171282459-973758fb-affc-4936-81dc-db343f3c91a8.png)

**Comment by ray-kast** [comment]
The indexer binaries have a couple required arguments for external services we can't provide for dev environments.  The `--amqp-url` argument should be provided the URL of a running AMQP server which a validator running the Geyser plugin is sending messages to.  The `--network` parameter should be the name of the network that validator is connected to (e.g. `mainnet`).

**Comment by shohidulbari** [comment]
@ray-kast Thank you so much for the response. So do we need to pass the --amqp-url and --network at the time of geyser plugin build? What is about --sender arguments?

**Comment by shohidulbari** [comment]
@ray-kast Where do I provide these --amqp-url, --network, --sender arguments. I tried with every command, it is saying,

**Comment by shohidulbari** [comment]
@ray-kast I added AMQP_URL, NETWORK and SENDER env variable and that error is gone now. But I am getting another error,
[holaplex_indexer_core] Invalid queue type for operation: Debug builds must specify a unique debug suffix for all AMQP names
Can you help me in that?

**Comment by ray-kast** [comment]
@shohidulbari Ah, yeah, that's a feature we installed to prevent development builds of our indexer from interfering with our production cluster.  The easiest way to resolve that error is to compile and run the crates in release mode (i.e. the cargo `--release` flag).

**Comment by shohidulbari** [comment]
@ray-kast I tried re-build with,
`cargo build --release -pholaplex-indexer-rabbitmq-geyser`
But still I am getting that error,

**Comment by shohidulbari** [comment]
@ray-kast Well, I have used the --release flag in every command and now the indexer is running. In RabbitMQ also I can see the queues and connections. But I am not seeing any messages there exchanging. I am using devnet as network. What should be the SENDER env variable? I am using the same AMQP_URL as the sender.

**Comment by shohidulbari** [comment]
@ray-kast No, I thought there is a default one for testing. So, do I need to set up a validator? Do you have any documentation which can help in this? Thanks in advance.

**Comment by mpwsh** [comment]
closing, let me know if more info is required @shohidulbari
