### ISSUE TITLE
Hasura Based Caching

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/indexer#622]
## Goals
Use Hasura Cloud to cache responses using TTL.

**Comment by echohtp** [comment]
redis would be a good solution 

any thoughts about:

- key structure? (im thinking query md5sum or something)
- data TTL?

**Comment by kespinola** [comment]
Use hasura as a cache layer that proxies our api adds caching directives to queries

https://hasura.io/graphql/caching/

**Comment by kespinola** [comment]
https://docs.stellate.co

Another graphql caching service

**Comment by dandlezzz** [comment]
@kespinola stellate looks cool. Do you know if its open source? I couldn't really tell. Also, Hasura looks promising, I know in prod we saw that Hasura adds latency to each request. @mpwsh  any idea what it would take to resolve those?

**Comment by mpwsh** [comment]
We could spin up Hasura in our kubes cluster for the stage env and start testing there. Hasura Cloud with VPC Peering is pretty expensive

**Comment by mpwsh** [comment]
@dandlezzz dammit
 it seems Hasura built in caching [is only available for cloud](https://github.com/hasura/graphql-engine/issues/4660#issuecomment-1100875171).
 Back to square one? Redis? will continue researching different options

**Comment by dandlezzz** [comment]
solved this with stellate. Closing.

**Comment by kespinola** [comment]
Exploring alternative options. Hasura max cache size is 100MB and $10k per month.
