### ISSUE TITLE
Support for non-MCC collections

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/indexer#676]
### Goal

NFTs that are naturally part of a collection but not tracked by a Metaplex Certified Collection NFT are still represented within the Holaplex NFT index.

As close as possible 1-1 parity of collections as with Magic Eden.

### To Do

- [x] Strategy for grouping non-mcc collections into collections
- [x] Document our strategy for forming non-mcc collections
- [x] Generate non mcc table based on SQL script
- [x] Collection based queries account for non and mcc collections
- [x] SQL cron job to regenerate non mcc collections n times a day

**Comment by kespinola** [comment]
done.
