### ISSUE TITLE
Setup API Endpoint with Data from Indexer for External Teams to Build On

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/indexer#71]
# Goal
Get an endpoint set up that allows external teams to build things like this – https://buzzednfts.com/

![image](https://user-images.githubusercontent.com/10433154/150808436-261c0301-05ed-422d-8a72-fb6ab1c6caeb.png)

**Comment by ray-kast** [comment]
Closing, I believe most of this use case is served by the current GraphQL server.
