### ISSUE TITLE
Genopets Sort/Filter request 9/7

### ISSUE THREAD

**Issue by CSmith051** [holaplex/indexer#726]
What:
sort : totalKiHarvested, KiAvailableToHarvest (it is a calculation based on different parameters of the habitat as number of subhabitats and their level, the habitat level and if it is a genesis )
filters: hasHaverter, hasAlchemist, hasNoHarvester, hasNoAlchemist, hasMaxKi (again this is a calculation based on different parameters of the habitat as number of subhabitats and their level ... and KiHarvested)

**Comment by CSmith051** [comment]
Additional: 
Add a filter on: 
expiryTimestamp = 0 to recover habitat not 'activated'

**Comment by kespinola** [comment]
done https://github.com/holaplex/indexer/pull/757
