### ISSUE TITLE
Non-MCC Collections on Kubes Cron

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#739]
### Goal
Non MCC collections are recomputed every hour.

### Requirements
- Add non-mcc collection sql generator script into config map @imabdulbasit 
- Run a container with psql installed and access to writer db using kube cron
- Manage the cron as a argo app so have UI to explore the status of the cron

### Environments
- [x] Staging
- [ ] Production

**Comment by mpwsh** [comment]
Got queries from @imabdulbasit. 
### Cron job for Collections volume
- [1d _volume migration : every 5mins](https://github.com/holaplex/indexer/pull/734/files#diff-ee5386eab0ab7348479c4cd043ad3f38215fb86287961ebf9a962be18841d396)
- [7d_volume_migration : every 2 hours](https://github.com/holaplex/indexer/pull/734/files#diff-480c68badcefab6f98730b815c9b2fa0da99dcfbff9ef189f99c28695995bc91)
- [30d_volume migration : every 12 hours](https://github.com/holaplex/indexer/pull/734/files#diff-f9212e60d78de71ddef131945f20013424ed6d10f5f128368bfd2f2286831bc1)

### Cron job for ME Collections.
- It involves very expensive queries so maybe every 3-4 hours: [updating me_collections & me_metadata_collections migration](https://github.com/holaplex/indexer/blob/ccd45cd629ac649214d07f29ccbc29236d915205/crates/core/migrations/2022-08-30-181402_create_non_mcc_tables/up.sql)

-  every 6/12 hours: [collection_stats migration](https://github.com/holaplex/indexer/blob/ccd45cd629ac649214d07f29ccbc29236d915205/crates/core/migrations/2022-09-14-081546_add_me_collection_stats_table/up.sql)


Starting to work on the cronjobs.

**Comment by mpwsh** [comment]
Cronjobs added to kubes repo (dev)  after merging #744 #745 
![image](https://user-images.githubusercontent.com/13471075/190237045-8a57e2a6-6911-4332-9a3b-9acabca3aa42.png)

All cronjob manifests can be found [here](https://github.com/holaplex/kubes/tree/dev/indexer/mainnet/app/jobs) alongside the [script](https://github.com/holaplex/kubes/blob/dev/indexer/mainnet/app/jobs/psql-run-script.yaml) that downloads the migration and executes them with `psql`

**Comment by kespinola** [comment]
done. ty @mpwsh

**Comment by kespinola** [comment]
done.
