### ISSUE TITLE
Collection Stats on Kubes Cron

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#740]
### Goal
Non MCC collections are recomputed every hour.

### Requirements
- Add collection stats sql generator script into config map
- Run a container with psql installed and access to writer db using kube cron
- Manage the cron as a argo app so have UI to explore the status of the cron

### Environments
- [x] Staging
- [x] Production

**Comment by kespinola** [comment]
@imabdulbasit can you post the sql scripts that you want ran to this issue or directly to @mpwsh?

**Comment by mpwsh** [comment]
Cronjobs have been deployed on stage indexer. Waiting for `main` <- `dev` merge to deploy the prod ones.  
More info about the deployment and how to deploy new cronjobs in #739

**Comment by kespinola** [comment]
done.
