### ISSUE TITLE
Usage example for realms calls 

### ISSUE THREAD

**Issue by ndrabins** [holaplex/indexer#746]
Hi, 

trying to implement holaplex indexer for realms calls - specifically getting governances for a realm. 

Found this query: 

```query governances($addresses: [PublicKey!], $realms: [PublicKey!]) {
  governances(addresses: $addresses, realms: $realms) {
    address
    governedAccount
    proposalsCount
    votingProposalCount
    governanceConfig {
      ...GovernanceConfigFragment
    }
    realm {
      ...RealmFragment
    }
  }
}
```

Not sure what is expected for the `addresses` field though. Any help would be much appreciated. Thanks!

**Comment by imabdulbasit** [comment]
addresses expected Governance account pubkeys

**Comment by ndrabins** [comment]
Thanks for the reply @imabdulbasit. If the public keys of the governance are required to query them, how do you get those governance public keys to then request the data on them through the holaplex api?

**Comment by imabdulbasit** [comment]
Its not required. Its one of the filter. So, if you want to query governance account data then you can either pass pubkeys of those accounts or realm pubkeys to which those governances belong to.

**Comment by ndrabins** [comment]
> Its not required. Its one of the filter. So, if you want to query governance account data then you can either pass pubkeys of those accounts or realm pubkeys to which those governances belong to or both

Ah okay thank you. I thought the addresses param was required. I got it to work. Much appreciated!
