### ISSUE TITLE
Record Rewards Distributed for Reward Center

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#797]
### Goal
Track tokens rewarded to the buyer and seller for reward center when purchase completed.

### Requirements
- Create table to track `rewards_payouts` when a `purchase_ticket` is index
```
rewards_payouts
-----------------
id uuid
purchase_ticket varchar(48) [index]
metadata varchar(48)
reward_center varchar(48) [index]
buyer varchar(48) [index]
buyer_reward bigint
seller varchar(48) [index]
seller_reward bigint
associated_collection text [index]
created_at DateTime [index, now()]
```
- When indexing a purchase_ticket write a rewards_payout that caches information from the payout_ticket, reward_center, and NFT collection based on its current configuration settings of the reward center.
  1. Lookup of the reward center associated to the purchase ticket
  2. Calculate the buyer_reward and seller_reward based on the purchase_ticket amount and configuration options of the reward center
  3. Lookup MCC address or Non-MCC address for associated to the metadata being purchased

**Comment by imabdulbasit** [comment]
**associated_collection** column should not be in reward_payouts table as it may belong to non mcc collection and they are updated through cron job. So it might be possible that when purchase_ticket is indexed, the metadata ∉ me_collections at that time

**Comment by kespinola** [comment]
> @kespinola associated_collection column should not be in reward_payouts table as it may belong to non mcc collection and they are updated through cron job. So it might be possible that when purchase_ticket is indexed, the metadata ∉ me_collections at that time

Gotcha. That's fine since the rewards generated are going to be tracked in 1d, 7d, 30d intervals and cached on collection_trends so ok for queries to be slower when computing the rewards generated. Thanks.

**Comment by kespinola** [comment]
done.
