### ISSUE TITLE
Collection Query Performance Audit

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#849]
### Goal
Optimize queries related to collections to decrease their load time.

### Queries
- Collection NFTs
https://nightmarket.holaplex.dev/collections/degods/nfts
- Collection attributes
https://nightmarket.holaplex.dev/collections/degods/nfts
- Collection activities
https://nightmarket.holaplex.dev/collections/aldermages/activity

**Comment by imabdulbasit** [comment]
https://github.com/holaplex/indexer/pull/853

**Comment by kespinola** [comment]
improved collection attributes.

done.

Need to look act activities in follow up.
