### ISSUE TITLE
Last Sold Field on NFT Object

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#859]
### Goal
Clients can query lookup the last sale of an NFT.

### Requirements
- Add `last_sale` on Nft object
- Add dataloader for last_sale
- Query the last_sold_metadatas table returning the price, date as `LastSale` graphql object
- Add dataloader for purchase that takes the purchase_id and returns the purchase
- Expose `purchase` on last sale object

**Comment by kristianeboe** [comment]
https://github.com/holaplex/indexer/pull/860

**Comment by kespinola** [comment]
done.
