### ISSUE TITLE
Serve Search Images Through Asset Proxy

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#909]
### Goal
Images returned through search results for collections go through the asset proxy.

![Screen Shot 2022-11-24 at 11 34 11 AM](https://user-images.githubusercontent.com/2388118/203762468-8c36c59f-0297-45da-9f8c-0ff1373b2b97.png)

**Comment by MotleyLabs-Matt** [comment]
Working as expected



![Image](https://user-images.githubusercontent.com/113057635/206565563-e46a40b5-db84-46e7-8bf6-62734a1bf613.png)
