### ISSUE TITLE
Audit and Adjustment of Profile Offers Queries

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#922]
### Goal
Profiles offer query responds in 500ms.

### Requirements
- [x] Audit the current query speed and identify causes of slow response times
- [x] Draft proposal to speed up the query
- [x] Implement the proposal

**Comment by imabdulbasit** [comment]
rebuilt invalid indexes for offers table so that should make profile offers query faster.

**Comment by kespinola** [comment]
Backport the index changes.

**Comment by kespinola** [comment]
done.
