### ISSUE TITLE
Wrong old collection is returned from GraphQL API

### ISSUE THREAD

**Issue by serejke** [holaplex/indexer#938]
**Describe the bug**
NFT [GynMVTTE2CwNgSFVh1KGQMLZzUtAxJQoAvzxw7ttoR6m](https://explorer.solana.com/address/GynMVTTE2CwNgSFVh1KGQMLZzUtAxJQoAvzxw7ttoR6m/metadata)
belongs to collection [CfptkovjUCQ1n4rFGDB5xnVPcndERTCA6hoXpL6R4jqm](https://explorer.solana.com/address/CfptkovjUCQ1n4rFGDB5xnVPcndERTCA6hoXpL6R4jqm)

but GraphQL API returns [9MqMpF8ghs9xfq1sknyrPSq4FFAqbGFVxQwA9NjdNrmS](https://explorer.solana.com/address/9MqMpF8ghs9xfq1sknyrPSq4FFAqbGFVxQwA9NjdNrmS) as the NFT's collection

I use the following request [nftMintByAddress](https://docs.holaplex.com/#query-nftByMintAddress) using `graphql-request` library.

```
const query = gql`
    query nftByMintAddress($address: String!) {
      nftByMintAddress(address: $address) {
        mintAddress
        owner {
          address
        }
        collection {
          nft {
            mintAddress
          }
        }
      }
    }
`

  const data = await request(
    'https://graph.holaplex.tools/v1/graphql',
    query,
    {
      address: new PublicKey('GynMVTTE2CwNgSFVh1KGQMLZzUtAxJQoAvzxw7ttoR6m'),
    }
  );
```

Returns:
```
{
  "nftByMintAddress": {
    "mintAddress": "GynMVTTE2CwNgSFVh1KGQMLZzUtAxJQoAvzxw7ttoR6m",
    "owner": {
      "address": "AVMUeN3WnbaG8r23AZPoUdGqZcQNL5Y3Nzfhr2EDCuE7"
    },
    "collection": {
      "nft": {
        "mintAddress": "9MqMpF8ghs9xfq1sknyrPSq4FFAqbGFVxQwA9NjdNrmS"
      }
    }
  }
}
```

`9MqMpF8ghs9xfq1sknyrPSq4FFAqbGFVxQwA9NjdNrmS` indeed was the NFT's collection at some point, but then the NFT was moved to another collection and its metadata was destroyed.

But the Holaplex indexer did not notice the collection's update.

**Comment by serejke** [comment]
In this [transaction](https://solscan.io/tx/xQSwa55k42rJ2wTwz35B5MWQXdCPuyTfqRt2VQrgMCCxrRURj6TkmfoFvdExVTckWsLBbQhuiivDoDh9izWu5H2) the collection was set to `9MqMpF8ghs9xfq1sknyrPSq4FFAqbGFVxQwA9NjdNrmS`

In this [transaction](https://solscan.io/tx/MKX4mdXTPwAoH1dY3wtguzVkYSENAdRffg31qYvYzL2jvmZqTtvNhH6yJkGM3jxw36mat8mK71mHGKtZn9RLNUx) the collection was updated to `CfptkovjUCQ1n4rFGDB5xnVPcndERTCA6hoXpL6R4jqm`

**Comment by kespinola** [comment]
@imabdulbasit can you review this NFT? Review that it is a missed account index and not issue in our mcc updates?
